### ISSUE TITLE
CronExpression does not accept <unicode> type

### ISSUE THREAD

**Issue by murrple-1** [ericpruitt/cronex#3]
# Minimum Code
```python
from cronex import CronExpression
ce = CronExpression(u'* * * * *')
```

# Expected result
Code should run without issue

# Observed Result
Raises error as
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.python-virtualenvs/codebase/local/lib/python2.7/site-packages/cronex/__init__.py", line 107, in __init__
    self.string_tab = map(str.upper, [minutes, hours, dom, months, dow])
TypeError: descriptor 'upper' requires a 'str' object but received a 'unicode'
```

# Workaround
Simply convert your `unicode` to `str` for the time being
```python
from cronex import CronExpression
ce = CronExpression(u'* * * * *'.encode('utf-8))
```

If you are unsure if the object is of type `unicode` or `str`, you can still use the same method

```python
# `my_string` is defined elsewhere, it is possibly a <unicode> or <str> object
from cronex import CronExpression
ce = CronExpression(my_string.encode('utf-8'))
```

**Comment by ericpruitt** [comment]
Thanks for reporting this issue. It has been fixed in 22d188190e4cac12cc6774e6eb10a2e3a477f26b using a different approach that does not require finagling with string encodings. Please let me know if this change does not work for you.

**Comment by murrple-1** [comment]
Copied you changes into my codebase, and I can confirm it's no longer crashing. I will keep an eye out for additional issues, but nothing anticipated. Thanks!

Is there an ETA for when v0.1.1 will make it onto pypi?

**Comment by ericpruitt** [comment]
I didn't think to push it to PyPI. This has been done.
