### ISSUE TITLE
unit test currently failing

### ISSUE THREAD

**Issue by megahall** [ericpruitt/cronex#6]
Hello @ericpruitt,

Thanks so much for making this little library. It's very helpful.

I was working on a small missing feature needed to implement support for time jump tracking for the Vixie cron style local time tracking event loop algorithm, where non-wildcard and wildcard job execution changes intelligently in the presence of DST, transitions and most forward and reverse clock skew occurrences.

While I was testing my own changes, I noticed an original UT is failing in the unchanged code. I wanted to see if you could check it for a second so I could be sure the change I'd like to contribute will work properly for everyone.

Thanks,
@megahall

```
$ ./tests.py
...................F....
======================================================================
FAIL: test_periodics_month (__main__.test_testedmodule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests.py", line 116, in test_periodics_month
    self.assertFalse(testex.check_trigger(now_tuple[:5]))
AssertionError: True is not false

----------------------------------------------------------------------
Ran 24 tests in 0.035s

FAILED (failures=1)
```

**Comment by megahall** [comment]
I did some more investigation on this. I think I see what's happening:

It's checking for a job to trigger between `2014-01-10` and `2017-09-08` by moving `1,337` days.

That's `3 years, 7 months, 29 days` or `43 months` but the cron expression was `* * * %44 *` or every `44 months`.

**Comment by ericpruitt** [comment]
The repeaters in each field are independent of one another. Although you are correct n stating the difference is 3 years, 7 months, 29 days, what actually matters is the difference in calendar months:

    ~$ bc
    (2017 * 12 + 9) - (2014 * 12 + 1)
    44

The documentation reads "Triggers in different fields operate independently of each other: %10 %10 * * * would trigger at 00:00, 00:10, ... 00:50, 10:00, 10:10, etc..." In the source code, the calculation reflects this on line 177:

```python
174         # Figure out how much time has passed from the epoch to the given date
175         utc_diff = utc_offset - self.epoch[5]
176         mod_delta_yrs = year - self.epoch[0]
177         mod_delta_mon = month - self.epoch[1] + mod_delta_yrs * 12
178         mod_delta_day = (given_date - zeroday).days
179         mod_delta_hrs = hour - self.epoch[3] + mod_delta_day * 24 + utc_diff
180         mod_delta_min = mins - self.epoch[4] + mod_delta_hrs * 60
```

Let me know if I misunderstood the problem. Otherwise, let me know if this makes sense, and I'll fix the unit test.

**Aside:** _I think making unit tests depend on the current time is yet another of many mistakes I made creating this library `:P`. I should really wrap up the rewrite I started for https://github.com/ericpruitt/cronex/issues/4 ._

**Comment by megahall** [comment]
At least on my machine the test wasn't passing by itself at the current moment. 

Matthew Hall

**Comment by ericpruitt** [comment]
> At least on my machine the test wasn't passing by itself at the current moment.

Right, the test is undoubtedly broken:

```sh
~$ date --date='2017-09-08' +%s
1504854000
```

```diff
diff --git cronex/tests.py cronex/tests.py
index 0d04d1f..ed3e341 100755
--- cronex/tests.py
+++ cronex/tests.py
@@ -104,7 +104,7 @@ class test_testedmodule(unittest.TestCase):
         Verify that arbitrary-period repeaters in the month field work as
         expected.
         """
-        now = int(time.time())
+        now = int(1504854000)
         then = time.gmtime(now - 1337 * DAY)
         now_tuple = time.gmtime(now)
         curmon = now_tuple[1]
```
```python
# FAIL: test_periodics_month (__main__.test_testedmodule)
# ---------------------------------------------------------------------
Traceback (most recent call last):
  File "cronex/tests.py", line 116, in test_periodics_month
    self.assertFalse(testex.check_trigger(now_tuple[:5]))
AssertionError: True is not false

# ----------------------------------------------------------------------
Ran 1 test in 0.000s
```

I was explaining how the code is supposed to work to ensure I understood the problem you were reporting and to ensure I fixed the correct thing. I will push a fix for the test soon.

**Comment by ericpruitt** [comment]
This has been fixed in dd3e719d17d8400083bc8876f7356d69f1fe30e5 . Please try it out and let me know if you observe any other problems. Thank you for reporting this issue.

**Comment by megahall** [comment]
Sorry about the miscommunication from my end. It took me a good couple of hours to try to figure it out how it was happening in the first place!

Matthew Hall

**Comment by ericpruitt** [comment]
No problem. If you use PyPI, I have just pushed the updated package as 0.1.2.
