### ISSUE TITLE
cp cronex.py `python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`

### ISSUE THREAD

**Issue by yaoyi2008** [ericpruitt/cronex#8]
When I exec this command, I got the error:

cp: 无法获取'cronex.py' 的文件状态(stat): 没有那个文件或目录

How to resolve it?

**Comment by ericpruitt** [comment]
This is not the correct way to install the library. Run `python setup.py install` to install the library globally or run `python setup.py install --user` to install the library just for the current user.
